module.exports = (robot) =>
{
	robot.registerGuide( "conditions", "insert rules for status conditions here");
		robot.registerGuide( "blinded", "A blinded character suffers a penalty of -3k3 to all ranged attack rolls and -1k1 to melee attack rolls. A blind character's base Armor TN is equal to his Reflexes Trait plus 5 (armor adds bonuses as normal). The character's Water Ring is considered two ranks lower for the purpose of determining how far he can move as part of a Move Action. Any attempt at a Simple Move Action requires an Athletics/Agility roll (TN 20) or the character is knocked Prone.");
		robot.registerGuide( "dazed", "A dazed character suffers a penalty of -3k0 to all actions. Dazed characters can only use the Defense and Full Defense Stances and cannot perform an laijutsu duel. The character may recover from this Status Effect by making a successful Earth Ring Roll versus a TN of 20 during the Reaction Stage. The target may attempt this roll once each Round, and the TN decreases by 5 each time he fails the roll.");
		robot.registerGuide( "entangled", "An entagled character can take no Actions other than attempting to break free. This is a Strength roll against a TN determined by the GM based on the nature of the entanglement; it is a Contested Roll if someone else is actively trying to keep the character entangled. Opponents may initiate a grapple with an entangled character without an attack roll.");
		robot.registerGuide( "fasting", "A character who goes without food and water for 24 hours loses the ability to regain Void Points from rest. although they can still be regained from meditation. After two days of fasting, a character suffers a +5 TN penalty to all his Skill rolls, physical Trait rolls, and Spell Casting Rolls until he gets food and drink. This increases by +5 for each additional day of fasting. After a number of days of fasting equal to his Stamina, he begins losing 2k 1 Wounds per day until he gets food and drink or dies.");
		robot.registerGuide( "fatigued", "A character who goes without rest for 24 hours suffers a +5 TN penalty to all his Skill rolls, physical Trait rolls, and Spell Casting Rolls until he rests. This penalty increases by an additional +5 for every day that passes without rest. After a number of days equal to the character's Stamina Trait, he must begin making Willpower Trait Rolls at TN 20 every two hours to avoid falling asleep. A fatigued character may not take the Full Attack Stance.");
		robot.registerGuide( "grappled", "A character who is participating in a grapple are much easier to hit with attacks, and have their Armor TN reduced to 5 plus any bonuses from armor they are wearing.");
		robot.registerGuide( "mounted", "A character sitting atop a horse or other mount, or who is on higher ground (at least a four foot height advantage), gains a bonus of +1k0 on attack rolls against un-mounted/lower characters. A mounted character may not use the Full Attack Stance.");
		robot.registerGuide( "prone", "A prone character is lying flat on his back, side, or stomach, and cannot move, attack, or defend himself to full effect. A prone character immediately suffers a -10 penalty to his Armor TN against melee attacks. This penalty lasts until he stands up. He cannot use Move Actions, and may only adopt the Defense or Attack Stances. He cannot attack with large weapons, and suffers a -2k0 penalty to attacks with medium and small weapons. It requires a Simple Action to stand up from the prone position.");
		robot.registerGuide( "stunned", "A character who is stunned may take no actions. Such a character has an Armor TN equal to 5 plus any bonuses from armor worn. The character may recover from this Status Effect by making a successful Earth Ring Roll at TN 20 during the Reaction Stage. If he fails this roll, the status ends at the end of the next Combat Round.");
		robot.registerGuide( "fear", "Fear effects have ranks, from 1 to 10. To resist, roll Willpower against a TN of 5 + (5x the Fear rank). Samurai can add their Honor rank to the roll./nIf the roll fails, the samurai suffers a penalty equal to the Fear rank in dice to all rolled dice. If the roll fails by 15 or more, the samurai either flees or cowers helplessly.");
	
	//robot.registerGuide( "", "");




}